using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.Extensions.DependencyInjection;

namespace Wolfgang.Audit.Schema;

#if NET8_0_OR_GREATER



/// <summary>
/// Installs or upgrades the audit schema (<c>AuditHeader</c>,
/// <c>AuditDetail</c>, and <c>__AuditSchemaVersion</c>) in the target database.
/// Provider-agnostic: the DDL is generated by EF Core's own
/// <see cref="IMigrationsSqlGenerator"/>, supplied by whichever provider
/// (<c>UseSqlServer</c>, <c>UseNpgsql</c>, <c>UseMySql</c>, <c>UseSqlite</c>, …)
/// was wired up on the <see cref="AuditMigrationsDbContext"/>.
/// </summary>
/// <remarks>
/// <para>
/// v1 ships with a single schema version
/// (<see cref="AuditSchemaConstants.CurrentSchemaVersion"/>). Fresh installs
/// diff an empty model against the current model — EF Core produces
/// <c>CreateTable</c> / <c>CreateIndex</c> / <c>AddForeignKey</c> operations
/// that the provider's SQL generator turns into provider-appropriate DDL.
/// </para>
/// <para>
/// Idempotent: a second call after a successful install reads the version row,
/// sees the schema is current, and exits without executing any SQL.
/// </para>
/// </remarks>
public static class AuditSchemaMigrator
{
    /// <summary>
    /// Applies any pending audit-schema migrations to the database backing
    /// <paramref name="context"/>.
    /// </summary>
    /// <param name="context">Migrations context configured for the target provider.</param>
    /// <param name="dryRun">When <c>true</c>, returns the SQL without executing.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async Task<string> RunAsync
    (
        AuditMigrationsDbContext context,
        bool dryRun = false,
        CancellationToken cancellationToken = default
    )
    {
        ArgumentNullException.ThrowIfNull(context);

        var installedVersion = await AuditSchemaVersionStore
            .ReadInstalledVersionAsync(context, cancellationToken)
            .ConfigureAwait(false);

        if (installedVersion >= AuditSchemaConstants.CurrentSchemaVersion)
        {
            return string.Empty;
        }

        var commands = GenerateCommands(context);

        if (dryRun)
        {
            return string.Join(";\n\n", commands.Select(c => c.CommandText));
        }

        await ApplyCommandsAsync(context, commands, cancellationToken).ConfigureAwait(false);
        return string.Empty;
    }



    private static IReadOnlyList<MigrationCommand> GenerateCommands(AuditMigrationsDbContext context)
    {
        var differ       = context.GetService<IMigrationsModelDiffer>();
        var sqlGenerator = context.GetService<IMigrationsSqlGenerator>();

        // EF Core 7+ split the runtime and design-time models. Migrations need
        // the design-time model (which retains the relational annotations the
        // differ inspects). EF Core 6 exposes only one model via context.Model
        // and that model already has the relational metadata.
#if NET8_0_OR_GREATER
        var targetModel = context.GetService<IDesignTimeModel>().Model;
#else
        var targetModel = context.Model;
#endif

        // v1: source model is null (empty). Future versions load the installed
        // snapshot for `installedVersion` instead, so the diff produces ALTER
        // operations rather than CREATE.
        var operations = differ.GetDifferences(
            source: null,
            target: targetModel.GetRelationalModel());

        return sqlGenerator.Generate(operations, targetModel);
    }



    private static async Task ApplyCommandsAsync
    (
        AuditMigrationsDbContext context,
        IReadOnlyList<MigrationCommand> commands,
        CancellationToken cancellationToken
    )
    {
        await context.Database.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
        try
        {
            await using var transaction = await context.Database
                .BeginTransactionAsync(cancellationToken)
                .ConfigureAwait(false);

            foreach (var command in commands)
            {
#pragma warning disable EF1002 // SQL is generated by EF Core's own SqlGenerator; not user input.
                await context.Database
                    .ExecuteSqlRawAsync(command.CommandText, cancellationToken)
                    .ConfigureAwait(false);
#pragma warning restore EF1002
            }

            await AuditSchemaVersionStore
                .UpsertInstalledVersionAsync(context, AuditSchemaConstants.CurrentSchemaVersion, cancellationToken)
                .ConfigureAwait(false);

            await transaction.CommitAsync(cancellationToken).ConfigureAwait(false);
        }
        finally
        {
            await context.Database.CloseConnectionAsync().ConfigureAwait(false);
        }
    }
}
#endif
