using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.Extensions.DependencyInjection;

namespace Wolfgang.Audit.Schema;

#if NET8_0_OR_GREATER



/// <summary>
/// Installs or upgrades the audit schema (<c>AuditHeader</c>,
/// <c>AuditDetail</c>, and <c>__AuditSchemaVersion</c>) in the target database.
/// Provider-agnostic: the DDL is generated by EF Core's own
/// <see cref="IMigrationsSqlGenerator"/>, supplied by whichever provider
/// (<c>UseSqlServer</c>, <c>UseNpgsql</c>, <c>UseMySql</c>, <c>UseSqlite</c>, …)
/// was wired up on the <see cref="AuditMigrationsDbContext"/>.
/// </summary>
/// <remarks>
/// <para>
/// v1 ships with a single schema version
/// (<see cref="AuditSchemaConstants.CurrentSchemaVersion"/>). Fresh installs
/// diff an empty model against the current model — EF Core produces
/// <c>CreateTable</c> / <c>CreateIndex</c> / <c>AddForeignKey</c> operations
/// that the provider's SQL generator turns into provider-appropriate DDL.
/// </para>
/// <para>
/// Idempotent: a second call after a successful install reads the version row,
/// sees the schema is current, and exits without executing any SQL.
/// </para>
/// </remarks>
public static class AuditSchemaMigrator
{
    /// <summary>
    /// Applies any pending audit-schema migrations to the database backing
    /// <paramref name="context"/>.
    /// </summary>
    /// <param name="context">Migrations context configured for the target provider.</param>
    /// <param name="dryRun">When <c>true</c>, returns the SQL without executing.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async Task<string> RunAsync
    (
        AuditMigrationsDbContext context,
        bool dryRun = false,
        CancellationToken cancellationToken = default
    )
    {
        ArgumentNullException.ThrowIfNull(context);

        var installedVersion = await AuditSchemaVersionStore
            .ReadInstalledVersionAsync(context, cancellationToken)
            .ConfigureAwait(false);

        if (installedVersion >= AuditSchemaConstants.CurrentSchemaVersion)
        {
            return string.Empty;
        }

        var commands = GenerateCommands(context);

        if (dryRun)
        {
            return string.Join(";\n\n", commands.Select(c => c.CommandText));
        }

        await ApplyCommandsAsync(context, commands, cancellationToken).ConfigureAwait(false);
        return string.Empty;
    }



    private static IReadOnlyList<MigrationCommand> GenerateCommands(AuditMigrationsDbContext context)
    {
        var differ       = context.GetService<IMigrationsModelDiffer>();
        var sqlGenerator = context.GetService<IMigrationsSqlGenerator>();

        // EF Core 7+ split the runtime and design-time models. Migrations need
        // the design-time model (which retains the relational annotations the
        // differ inspects). EF Core 6 exposes only one model via context.Model
        // and that model already has the relational metadata.
#if NET8_0_OR_GREATER
        var targetModel = context.GetService<IDesignTimeModel>().Model;
#else
        var targetModel = context.Model;
#endif

        // v1: source model is null (empty). Future versions load the installed
        // snapshot for `installedVersion` instead, so the diff produces ALTER
        // operations rather than CREATE.
        var operations = differ.GetDifferences(
            source: null,
            target: targetModel.GetRelationalModel());

        return sqlGenerator.Generate(operations, targetModel);
    }



    private static Task ApplyCommandsAsync
    (
        AuditMigrationsDbContext context,
        IReadOnlyList<MigrationCommand> commands,
        CancellationToken cancellationToken
    )
    {
        // Route through IExecutionStrategy so this composes with SQL Server's
        // EnableRetryOnFailure (or any other retrying strategy). Directly
        // calling BeginTransactionAsync on a context configured with a retrying
        // strategy throws — EF Core requires the whole transactional operation
        // to be wrapped so the strategy can re-run it on transient failures.
        var strategy = context.Database.CreateExecutionStrategy();
        return strategy.ExecuteAsync(
            (Context: context, Commands: commands),
            static async (_, state, ct) =>
            {
                await state.Context.Database.OpenConnectionAsync(ct).ConfigureAwait(false);
                try
                {
                    // MA0004: see the matching note in DbContextAuditSchemaExtensions —
                    // `await using var` cannot ConfigureAwait the implicit DisposeAsync.
                    var transaction = await state.Context.Database
                        .BeginTransactionAsync(ct)
                        .ConfigureAwait(false);
                    await using var configuredTx = transaction.ConfigureAwait(false);

                    foreach (var command in state.Commands)
                    {
#pragma warning disable EF1002 // SQL is generated by EF Core's own SqlGenerator; not user input.
                        await state.Context.Database
                            .ExecuteSqlRawAsync(command.CommandText, ct)
                            .ConfigureAwait(false);
#pragma warning restore EF1002
                    }

                    await AuditSchemaVersionStore
                        .UpsertInstalledVersionAsync(state.Context, AuditSchemaConstants.CurrentSchemaVersion, ct)
                        .ConfigureAwait(false);

                    await transaction.CommitAsync(ct).ConfigureAwait(false);
                }
                finally
                {
                    await state.Context.Database.CloseConnectionAsync().ConfigureAwait(false);
                }

                return 0; // ExecuteAsync<TState, TResult> needs a return value; the migrator is fire-and-forget.
            },
            verifySucceeded: null,
            cancellationToken: cancellationToken);
    }
}
#endif
